// <auto-generated />
using System;
using CoreCourse.Spyshop.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCourse.Spyshop.Web.Migrations
{
    [DbContext(typeof(SpyShopContext))]
    partial class SpyShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreCourse.Spyshop.Domain.Catalog.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1L, Name = "Cameras" },
                        new { Id = 2L, Name = "Communication" },
                        new { Id = 3L, Name = "Distraction" },
                        new { Id = 4L, Name = "General" },
                        new { Id = 5L, Name = "Navigation" }
                    );
                });

            modelBuilder.Entity("CoreCourse.Spyshop.Domain.Catalog.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CategoryId")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("SortNumber");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1L, CategoryId = 1L, Description = "The built-in camera in this watch transmits a secured videofeed to a nearby monitor.", Name = "Spywatch", PhotoUrl = "watch.jpg", Price = 39.95m, SortNumber = 1 },
                        new { Id = 2L, CategoryId = 1L, Description = "The built-in camera in this watch transmits a secured videofeed to a nearby monitor. Videos can be saved locally on a microchip.", Name = "Spywatch with storage", PhotoUrl = "watch.jpg", Price = 39.95m, SortNumber = 2 },
                        new { Id = 3L, CategoryId = 1L, Description = "This camera is waterproof to an astounding 700m, and runs entirely on hydrogen extracted by the environment.", Name = "Underwater camera", Price = 111.95m, SortNumber = 3 },
                        new { Id = 4L, CategoryId = 1L, Description = "When reaching an altitude of 1,5 km, this camera sends a live feed of the environment while parachuting down.", Name = "Rocketchute \"Bird's eye\"", Price = 7.95m, SortNumber = 4 },
                        new { Id = 5L, CategoryId = 1L, Description = "Easy to hide and mount IR camera.", Name = "Infrared camera", Price = 15.95m, SortNumber = 5 },
                        new { Id = 6L, CategoryId = 2L, Description = "A small transmitter shaped as a pencil. Speak in the tip and listen at the other end. Also writes.", Name = "Communication pencil", PhotoUrl = "pencil.jpg", Price = 6.95m, SortNumber = 1 },
                        new { Id = 7L, CategoryId = 2L, Description = "Point this pen at your discussion partner to convince him of your point of view. Writes in blue ink.", Name = "Point of view pen", PhotoUrl = "pen.jpg", Price = 9.95m, SortNumber = 2 },
                        new { Id = 8L, CategoryId = 2L, Description = "Evil geniuses have cats. Distract them with this laser pointer. Disperses catnip as a last resort.", Name = "Cigar laserpointer", PhotoUrl = "cigar.jpg", Price = 13.95m, SortNumber = 3 },
                        new { Id = 9L, CategoryId = 2L, Description = "Advanced voice-technology ensures this moustasche translates every word you say in the language of choice.", Name = "Mustasch Translator", PhotoUrl = "stash.jpg", Price = 73.95m, SortNumber = 4 },
                        new { Id = 10L, CategoryId = 2L, Description = "Hang these low profile ear rings and translate every word to a preset language whispered in your ear.", Name = "Earring Translator", PhotoUrl = "earrings.jpg", Price = 93.95m, SortNumber = 5 },
                        new { Id = 11L, CategoryId = 2L, Description = "Put this robotic fish-shaped device in your ear and understand any language.", Name = "Babelfish", Price = 123.95m },
                        new { Id = 12L, CategoryId = 2L, Description = "A tiny cellphony with tracking capabilities.", Name = "Cellphone with tracking", PhotoUrl = "tinyphone.jpg", Price = 33.95m },
                        new { Id = 13L, CategoryId = 3L, Description = "A small button underneath activates a hologram where you were previously seated.", Name = "Holographic cushion", PhotoUrl = "cushion.jpg", Price = 69.95m, SortNumber = 1 },
                        new { Id = 14L, CategoryId = 3L, Description = "One small drip of this liquid on the nose of your victim and he will tell you no more lies. Works best on long noses.", Name = "Correction liquid", PhotoUrl = "corrliq.jpg", Price = 129.95m, SortNumber = 2 },
                        new { Id = 15L, CategoryId = 3L, Description = "When an enemy approaches you, simply switch on this device to confuse him. He will identify you as friendly.", Name = "Identity Scrambler", PhotoUrl = "idscramble.jpg", Price = 145.95m, SortNumber = 3 },
                        new { Id = 16L, CategoryId = 3L, Description = "Place banknotes in this wallet. Place this in the fridge overnight to have them turn into the local currency.", Name = "Exchange wallet", PhotoUrl = "wallet.jpg", Price = 29.95m, SortNumber = 4 },
                        new { Id = 17L, CategoryId = 3L, Description = "Place mentos in cola bottle. Point at target to distract.", Name = "Cola and mentos", Price = 1.95m, SortNumber = 5 },
                        new { Id = 18L, CategoryId = 4L, Description = "The lenses allow to you to zoom up to 5 km.", Name = "Zooming contactlenses", PhotoUrl = "lenses.jpg", Price = 73.95m },
                        new { Id = 19L, CategoryId = 4L, Description = "Put a bandage on a wound and wait 10 to 30 minutes. Your injury will be fully healed.", Name = "Quick Bandages", Price = 12.95m },
                        new { Id = 20L, CategoryId = 4L, Description = "A must-have when mingling with wealthy, evil geniuses.", Name = "Bulletproof tuxedo", Price = 133.95m },
                        new { Id = 21L, CategoryId = 4L, Description = "This card game targets a specific person and lets him to win or lose. Comes with a mobile app.", Name = "Card game", Price = 70.95m },
                        new { Id = 22L, CategoryId = 5L, Description = "Analyses signals sent to satellites. ", Name = "Satellite Monitor", Price = 25.95m, SortNumber = 1 },
                        new { Id = 23L, CategoryId = 5L, Description = "Tracks your accurate altitude and position in every landscape.", Name = "Offroad GPS", PhotoUrl = "gps.jpg", Price = 15.95m, SortNumber = 2 },
                        new { Id = 24L, CategoryId = 5L, Description = "Tracks your accurate altitude and position using the Galileo satellites.", Name = "Galileo tracer", Price = 25.95m, SortNumber = 3 },
                        new { Id = 25L, CategoryId = 5L, Description = "These batteries (available in AA and AAA) send accurate positioning signals to the satellites of your choice.", Name = "Tracer Batteries", PhotoUrl = "batteries.jpg", Price = 29.95m, SortNumber = 4 }
                    );
                });

            modelBuilder.Entity("CoreCourse.Spyshop.Domain.Catalog.Product", b =>
                {
                    b.HasOne("CoreCourse.Spyshop.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
